[package]
name = "bfs"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = "1.17.0"
rayon = "1.11.0"
thread_local = "1.1.9"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bfs_grid"
harness = false

[profile.profiling]
inherits = "release"
debug = true
